# Generated by Django 5.1.2 on 2024-11-04 21:20

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/home/propolisss/askme_voevodin/uploads')),
        ),
    ]
