# Generated by Django 5.1.2 on 2024-11-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='is_liked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='is_liked',
            field=models.BooleanField(default=True),
        ),
    ]
