# Generated by Django 5.1.2 on 2024-11-09 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_answerlike_is_liked_questionlike_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlike',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_likes', to='app.profile'),
        ),
    ]
